config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments
  end
  
  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments
  has_attached_file :image, styles: { medium: "700x500#", small: "350x250#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    
    if @comment.save
      redirect_to @post
    else
      render 'new'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @posts = Post.all.order("created_at DESC")
  end
  
  def show
    @comments = Comment.where(post_id: @post)
  end
  
  def new
    @post = current_user.posts.build
  end
  
  def create
    @post = current_user.posts.build(post_params)
    
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  def destroy
    @post.destroy
    redirect_to root_path
  end
  
  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end
  
  def downvote
    @post.downvote_by current_user
    redirect_to :back
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :link, :description, :user_id, :image)
  end
  
  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
  = f.input :content, label: "Reply to thread"
  = f.button :submit, class: "button"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Muse
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
  %link{:rel => "stylesheet", :href => "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"}
  %link{:rel => "stylesheet", :href => "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css"}
  = csrf_meta_tags 

%body
  %header
    .wrapper.clearfix
      #logo= link_to "Muse", root_path
      %nav
        - if user_signed_in?
          = link_to current_user.name, edit_user_registration_path
          = link_to "Add New Inspiration", new_post_path, class: "button"
        - else
          = link_to "Sign In", new_user_session_path
          = link_to "Sign Up", new_user_registration_path, class: "button"
  %p.notice= notice
  %p.alert= alert
  = yield 

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :image
  = f.input :title
  = f.input :link
  = f.input :description
  = f.button :submit

app/views/posts/edit.html.haml
%h1 Edit post

= render 'form'

app/views/posts/index.html.haml
- @posts.each do |post|
  = link_to (image_tag post.image.url(:small)), post
  %br
  %h3= link_to post.title, post
  %p
    = post.comments.count
    Comments
  %br
  %p
    = post.get_upvotes.size
    Likes

  
  = link_to "Delete", post_path(post), method: :delete, data: { confirm: "Are you sure?" }
  = link_to "Edit", edit_post_path(post)
  %br

%br

= link_to "New post", new_post_path

app/views/posts/new.html.haml
%h1 Add New Inspiration

= render 'form'

app/views/posts/show.html.haml
= image_tag @post.image.url(:medium)
%h1= @post.title
%p= @post.link
%p= @post.description
%br
%p= @post.user.name
%p
  = @post.get_upvotes.size
  Likes
%p
  = @post.get_downvotes.size
  Dislikes
= link_to "Like", like_post_path, method: :put
= link_to "Dislike", dislike_post_path, method: :put

#comment
  %h2.comment_count= pluralize(@post.comments.count, "comment")
  - @comments.each do |comment|
    .comment
      %p.username= comment.user.name
      %p.content= comment.content
      
  = render 'comments/form'

= link_to "Back", root_path
= link_to "Edit", edit_post_path(@post)
= link_to "Delete", posts_path(@post), method: :delete, data: { confirm: "Are you sure?" }